name: DecSecOps-CI

on: [push]

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v6.0.0
      with: 
       python-version: 3.8

    - name: Intall Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: upload scan report 
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
  
  image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-22.04

   steps:
   - name: Checkout code
     uses: actions/checkout@v2
     
   - name: Docker Setup Docker
     uses: docker/setup-docker-action@v4.4.0

   - name: Docker build
     run: docker build -f Dockerfile -t myapp:01 . 
     

    
      
      
    
      
    
    
    
    
    
